### PR TITLE
fix: forward shell env to pager

### LINKED ISSUE #129: `WARNING: terminal is not fully functional` when `motd.pager.bin = "less"`
**What happened**
After tapping my security key, I see "WARNING: terminal is not fully functional" and "Press RETURN to continue". Pressing any key then displays the MotD, but without any terminal colors.

**What I expected to happen**
After tapping my security key, I expect to see the MotD (in color) next.

**To Reproduce**
1. ChromeOS Version 127.0.6533.114 (Official Build) (64-bit)
2. ".config/shpool/config.toml" is `[motd.pager] bin = "less"` (config file does have a new-line, but removed here for formatting)
3. Secure Shell Version 0.67 (from https://chromewebstore.google.com/detail/secure-shell/iodihamcpbpeioajjeobimgagajmlibd)
4. SSH Arguments `-t shpool attach -f login`
5. Connect

**Version info**
shpool 0.6.3 (cl/665149055)

**Logs**
[shpool.log](https://github.com/user-attachments/files/16715080/shpool.log)

### PR DESCRIPTION
**Pull request by ethanpailes**
This patch fixes the motd.pager mode to start launching the pager with the same environment that we launch the shell with. The old way of just inheriting the same environment that the daemon has has the problem that it will not correctly match the user's TERM value, which can cause problems for programs like `less` that use the TERM value to determine the right control sequences to emit.

Fixes #129

### CODE REVIEW

File: libshpool/src/daemon/server.rs [hunk 1]
```diff
@@ -659,7 +666,8 @@ impl Server {
             // to avoid breakage and vars the user has asked us to inject.
             .env_clear();
 
-        let term = self.inject_env(&mut cmd, &user_info, header).context("setting up shell env")?;
+        let term = shell_env.iter().filter(|(k, _)| k == "TERM").map(|(_, v)| v).next();
+        cmd.envs(shell_env.to_vec());
```
Comment (jrmlhermitte) [inline libshpool/src/daemon/server.rs:670]: (no action needed, unless this is not correct) It seems like you're creating the env, then injecting it into the shell anyway. I like this separation, nice job

File: libshpool/src/daemon/server.rs [hunk 2]
```diff
@@ -823,29 +831,35 @@ impl Server {
 
     /// Set up the environment for the shell, returning the right TERM value.
     #[instrument(skip_all)]
-    fn inject_env(
+    fn build_shell_env(
```
Comment (jrmlhermitte) [inline libshpool/src/daemon/server.rs:834]: (no action needed)
If I understand, we're rather creating the env vars we need and passing them around before injecting them (later), nice.

File: libshpool/src/daemon/pager.rs [hunk 3]
```diff
@@ -128,6 +130,7 @@ impl Pager {
         msg_file.write_all(cleaned_msg.as_slice()).context("writing msg to tmp pager file")?;
 
         let mut cmd = process::Command::new(&self.pager_bin);
+        cmd.env_clear().envs(shell_env.to_vec());
```
Comment (jrmlhermitte) [inline libshpool/src/daemon/pager.rs:133]: (no action needed)
just making sure i understand, unlike the shell where we inject the env, here we clear and insert only the shpool-created env variables. and this is to satistfy the TERM override issue mentioned in the description

i like this separation and how easy it is to read what is done

File: libshpool/src/daemon/server.rs [hunk 4]
```diff
@@ -612,9 +618,10 @@ impl Server {
         conn_id: usize,
         client_stream: UnixStream,
         header: &AttachHeader,
+        user_info: &user::Info,
+        shell_env: &[(String, String)],
```
Comment (jrmlhermitte) [inline libshpool/src/daemon/server.rs:622]: minor nit: maybe call it `supplemental_env` or emphasize in the docstrings that these are the shpool specific shell envs, but that otherwise any other envs from the spawning shell are inherited?

File: shpool/tests/data/motd_env_test_script.sh [hunk 5]
```diff
@@ -0,0 +1,5 @@
+#!/bin/bash
+
+echo "TERM=${TERM}"
+
+sleep 5
```
Comment (jrmlhermitte) [inline shpool/tests/data/motd_env_test_script.sh:5]: this is going to increase test time. is 5 seconds needed?

is there any chance this test might be repeated over multiple parameters in the future?

I think this is fine, just want to make sure we don't have any issues that may reduce feasibility at any increase in scale

File: shpool/tests/data/motd_pager_env_test.toml.tmpl [hunk 6]
```diff
@@ -0,0 +1,11 @@
+norc = true
+noecho = true
+shell = "/bin/bash"
+session_restore_mode = "simple"
+
+[motd.pager]
+bin = "MOTD_ENV_TEST_SCRIPT"
+
+[env]
+PS1 = "prompt> "
```
Comment (jrmlhermitte) [inline shpool/tests/data/motd_pager_env_test.toml.tmpl:10]: very clear.


any chance we can also add comments at the top of this file to say more on the intent? (although it can help reading, it is okay if we can't, since the test that calls it is the source of truth)

File: shpool/tests/attach.rs [hunk 7]
```diff
@@ -1433,6 +1433,51 @@ fn motd_debounced_pager_unbounces() -> anyhow::Result<()> {
     })
 }
 
+#[test]
+#[timeout(30000)]
+fn motd_env_test_pager() -> anyhow::Result<()> {
```
Comment (jrmlhermitte) [inline shpool/tests/attach.rs:1438]: nit: should we call is `modt_env_test_pager_preserves_term_env_var` or similar since i think that is principally what is is testing?

**Review by jrmlhermitte — APPROVED** [review]
looks good, very clean, nice job!

File: libshpool/src/daemon/server.rs (hunk 1 above)
Comment (ethanpailes) [reply libshpool/src/daemon/server.rs:670]: yeah

File: libshpool/src/daemon/pager.rs (hunk 3 above)
Comment (ethanpailes) [reply libshpool/src/daemon/pager.rs:133]: Yeah pretty much. I think it might not be horrible to inherit from the daemon, but this way seems a little more predictable.

File: shpool/tests/attach.rs (hunk 7 above)
Comment (ethanpailes) [reply shpool/tests/attach.rs:1438]: Yeah good idea, thanks!
