### PR TITLE
fix: eval SHPOOL__OLD_PROMPT_COMMAND rather than iterate sub-components

### LINKED ISSUE #95: [Issue] printf: usage: printf [-v var] format [arguments]
**What happened**
Running `shpool attach test` shows this message, and the message repeats on every command

image

Running "bash" on the attached session fixes the issue.

It seems to be related to my PS1 maybe?

`\[\e[01;31m\][\u@\h\[\e[m\]\[\e[0;34m\]:\w\[\e[m\]\[\e[01;31m\]]# \[\e[m\]`

I see that a hacker news user has the same issue https://news.ycombinator.com/item?id=40728456

**To Reproduce**

Followed installation instructions on Rocky 9.4

**Version info**
Run `shpool version` and paste the output here

shpool 0.6.3

**Logs**

```
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.369027Z  INFO ThreadId(01) run:serve: socket got a new connection
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.369181Z  INFO ThreadId(57) handle_conn{cid=11}: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.369198Z  INFO ThreadId(57) handle_conn{cid=11}:parse_connect_header: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.369232Z  INFO ThreadId(57) handle_conn{cid=11}:parse_connect_header: close time.busy=30.1µs time.idle=4.38µs
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.369267Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.369271Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach: locked shells table
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.369274Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach: no existing 'x' session, creating new one
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.369276Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach: creating new subshell
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.369279Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.369315Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell: user_info=Info { default_shell: "/bin/bash", home_dir: "/root", user: "root" }
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.369324Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell:inject_env: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.369334Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell:inject_env: injecting TERM into shell Some("xterm-256color")
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.369344Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell:inject_env: close time.busy=17.4µs time.idle=3.19µs
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.369580Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell: about to fork subshell noecho=false
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.370509Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell: injecting prompt prefix
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.370537Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell:maybe_inject_prefix: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.370545Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell:maybe_inject_prefix:wait_for_startup: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.370667Z  INFO ThreadId(58) child_watcher{s="x" cid=11}: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com systemd[1]: Starting Hostname Service...
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com systemd[1]: Started Hostname Service.
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467198Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell:maybe_inject_prefix:wait_for_startup: close time.busy=96.6ms time.idle=4.66µs
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467218Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell:maybe_inject_prefix:sniff_shell: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467250Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell:maybe_inject_prefix:sniff_shell: shell_proc_name: bash
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467255Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell:maybe_inject_prefix:sniff_shell: close time.busy=33.2µs time.idle=4.50µs
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467269Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell:maybe_inject_prefix: close time.busy=96.7ms time.idle=9.54µs
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467280Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell:spawn_reader{s="x"}: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467346Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell:spawn_reader{s="x"}: close time.busy=62.3µs time.idle=3.58µs
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467356Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:spawn_subshell: close time.busy=98.1ms time.idle=2.91µs
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467363Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach: released lock on shells table
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467366Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:link_ssh_auth_sock: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467369Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:link_ssh_auth_sock: no SSH_AUTH_SOCK in client env, leaving it unlinked
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467372Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:link_ssh_auth_sock: close time.busy=2.94µs time.idle=2.81µs
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467375Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:write_reply: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467385Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:write_reply: close time.busy=6.96µs time.idle=2.70µs
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467388Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach: starting bidi stream loop
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467385Z  INFO ThreadId(59) reader{s="x" cid=11}: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.467391Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:bidi_stream{s="x"}: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.472112Z  INFO ThreadId(59) reader{s="x" cid=11}: waiting for initial client connection
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.472131Z  INFO ThreadId(59) reader{s="x" cid=11}: got initial client connection
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.472131Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:bidi_stream{s="x"}: client connection status=New
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.472139Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:bidi_stream{s="x"}:spawn_client_to_shell: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.472141Z  INFO ThreadId(59) reader{s="x" cid=11}: resized fd (rows=48, cols=180)
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.472191Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:bidi_stream{s="x"}:spawn_client_to_shell: close time.busy=47.4µs time.idle=4.56µs
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.472197Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:bidi_stream{s="x"}:spawn_heartbeat: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.472222Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:bidi_stream{s="x"}:spawn_heartbeat: close time.busy=22.4µs time.idle=2.94µs
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.472226Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:bidi_stream{s="x"}:spawn_supervisor: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.472227Z  INFO ThreadId(60) client->shell{s="x" cid=11}: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.472248Z  INFO ThreadId(57) handle_conn{cid=11}:handle_attach:bidi_stream{s="x"}:spawn_supervisor: close time.busy=19.6µs time.idle=2.80µs
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.472298Z  INFO ThreadId(62) supervisor{s="x" cid=11}: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.472318Z  INFO ThreadId(61) heartbeat{s="x" cid=11}: new
Jul 15 20:03:48 dg-lakeview-8v-s.nix.cccis.com shpool[37228]: 2024-07-15T20:03:48.472937Z  INFO ThreadId(59) reader{s="x" cid=11}: saw prompt sentinel
```

### PR DESCRIPTION
**Pull request by parrotmac**
👋 hey Ethan, awesome project! Excited to forget how to reconfigure tmux to have vim keybindings (that still don't really make sense to me 😅).

This PR attempts to fix #95

I was running into this same issue on some of my machines. Looks like some distros, when using bash, may set `$PROMPT_COMMAND` to something with whitespace. Though, I'm curious if there's a case where we wouldn't want to `eval ${PROMPT_COMMAND}`.

### ✅ Ubuntu Server (22.04)
```shell
builder@android-builder:~$ shpool attach main

shpool:main builder@android-builder:~$
builder@android-builder:~$ echo $PROMPT_COMMAND

builder@android-builder:~$ echo $PS1
\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$
```

### ✅ Ubuntu (on DigitalOcean's custom image)
```shell
root@bunt:~# echo $PROMPT_COMMAND

root@bunt:~# echo $PS1
\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\u@\h:\w\$
```

### ❗ Endeavour - Issue
```
[isaac@isaac-endeavour ~]$ shpool attach main

printf: usage: printf [-v var] format [arguments]
-bash: "\033]0;%s@%s:%s\007": command not found
-bash: "${USER}": command not found
-bash: "${HOSTNAME%%.*}": command not found
-bash: "${PWD/#$HOME/\~}": No such file or directory
[isaac@isaac-endeavour ~]$ echo $PROMPT_COMMAND
printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"
```

### ❗ Fedora release 41 (Forty One)
```
isaac@flow:~$ shpool attach main

printf: usage: printf [-v var] format [arguments]
-bash: "\033]0;%s@%s:%s\007": command not found
-bash: "${USER}": command not found
-bash: "${HOSTNAME%%.*}": command not found
-bash: "${PWD/#$HOME/\~}": No such file or directory
isaac@flow:~/shpool/shpool$ echo $PROMPT_COMMAND
printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"
isaac@flow:~/shpool/shpool$ echo $PS1
${PROMPT_START@P}\[\e[${PROMPT_COLOR}${PROMPT_HIGHLIGHT:+;$PROMPT_HIGHLIGHT}m\]${PROMPT_USERHOST@P}\[\e[0m\]${PROMPT_SEPARATOR@P}\[\e[${PROMPT_DIR_COLOR-${PROMPT_COLOR}}${PROMPT_HIGHLIGHT:+;$PROMPT_HIGHLIGHT}m\]${PROMPT_DIRECTORY@P}\[\e[0m\]${PROMPT_END@P}\$\[\e[0m\]
```

Here's the relevant snippet from Fedora's `/etc/bashrc`:
```bash
  if [ "$PS1" ]; then
    if [ -z "$PROMPT_COMMAND" ]; then
      declare -a PROMPT_COMMAND
      case $TERM in
      xterm*)
        if [ -e /etc/sysconfig/bash-prompt-xterm ]; then
            PROMPT_COMMAND=/etc/sysconfig/bash-prompt-xterm
        else
            PROMPT_COMMAND='printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'
        fi
        ;;
      screen*)
        if [ -e /etc/sysconfig/bash-prompt-screen ]; then
            PROMPT_COMMAND=/etc/sysconfig/bash-prompt-screen
        else
            PROMPT_COMMAND='printf "\033k%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'
        fi
        ;;
      *)
        [ -e /etc/sysconfig/bash-prompt-default ] && PROMPT_COMMAND=/etc/sysconfig/bash-prompt-default
        ;;
      esac
    fi
```

And from Endeavour's `/etc/bash.bashrc`
```bash
case ${TERM} in
  Eterm*|alacritty*|aterm*|foot*|gnome*|konsole*|kterm*|putty*|rxvt*|tmux*|xterm*)
    PROMPT_COMMAND+=('printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"')

    ;;
  screen*)
    PROMPT_COMMAND+=('printf "\033_%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"')
    ;;
esac
```

### CODE REVIEW

File: libshpool/src/daemon/prompt.rs [hunk 1]
```diff
@@ -67,12 +67,8 @@ pub fn maybe_inject_prefix(
...
                SHPOOL__OLD_PS1="${{PS1}}"
                function __shpool__prompt_command() {{
-                  PS1="${{SHPOOL__OLD_PS1}}"
-                  for prompt_hook in ${{SHPOOL__OLD_PROMPT_COMMAND}}
-                  do
-                    ${{prompt_hook}}
-                  done
-                  PS1="{prompt_prefix}${{PS1}}"
+                  eval "${{SHPOOL__OLD_PROMPT_COMMAND}}"
+                  PS1="{prompt_prefix}${{SHPOOL__OLD_PS1}}"
```
Comment (ethanpailes) [inline libshpool/src/daemon/prompt.rs:71]: This will clobber any effect that the old prompt command had on PS1 because it sets PS1 to the old PS1 value. If the prompt hook we are extending modifies PS1 in any way, that will no longer get picked up. This line should be

```
PS1="{prompt_prefix}${{PS1}}"
```

to fix that.

**Review by ethanpailes — COMMENTED** [review]
I'm concerned that this will cause a regression for the issue fixed by 7cbfecc3 (#25). It seems like sometimes PROMPT_COMMAND is a list of bash functions to invoke and sometimes it is a command with arguments.

Maybe this has to do with the way bash is stringly typed, so if it is a single string it is a command to be invoked, and if it is an array of strings it is a list of commands to be invoked?

Does the problem go away for you when you invoke SHPOOL_OLD_PROMPT_COMMAND like

```
for prompt_hook in "${{SHPOOL__OLD_PROMPT_COMMAND[@]}}"
do
    ${{prompt_hook}}
done
```

(or maybe you need to eval prompt_hook inside the loop).

**Comment by ethanpailes** [comment]
https://www.gnu.org/software/bash/manual/html_node/Controlling-the-Prompt.html makes it sound like PROMPT_COMMAND is supposed to be an array variable. It occurs to me that we might need to do something special to copy the array over as well. The current assignment from PROMPT_COMMAND to SHPOOL__OLD_PROMPT_COMMAND may be converting from an array to a single flat string.

File: libshpool/src/daemon/prompt.rs (hunk 1 above)
Comment (ethanpailes) [reply libshpool/src/daemon/prompt.rs:71]: Yeah, that looks like it will work:

```
$ arr=('echo hi' 'echo bye' 'echo blip bloop blop')
$ echo $(IFS="; "; echo "${arr[*]}")
echo hi;echo bye;echo blip bloop blop
$ eval "$(IFS="; "; echo "${arr[*]}")"
hi
bye
blip bloop blop
```

**Comment by parrotmac** [comment]
Thanks for the feedback @theJian, @cleeland and @ethanpailes!

From experimenting with the different approaches it looks like doing an `eval "${prompt_hook}"` produces the most faithful result.

I put together [a little test suite](https://github.com/parrotmac/shpool-hook-playground/blob/ad69e29cdb4435f5f38b043cf89d21757e44e5d2/hook.bats) to try different variations of the hook script.

Of note is that doing
```
        for prompt_hook in "${SHPOOL__OLD_PROMPT_COMMAND[@]}"
        do
            ${prompt_hook}
        done
```

with a simple `PROMPT_COMMAND`, such as
```
PROMPT_COMMAND="printf \"%s\" SIMPLEPROMPT"
````
would result in quotes around the output
```
"SIMPLEPROMPT"
```

This appears to be working correctly based on my own testing, but curious to hear from others

File: libshpool/src/daemon/prompt.rs [hunk 2]
```diff
@@ -68,9 +68,9 @@ pub fn maybe_inject_prefix(
                SHPOOL__OLD_PS1="${{PS1}}"
```
Comment (ethanpailes) [inline libshpool/src/daemon/prompt.rs:68]: (This comment is really for line 67).

I think the array copy on line 67 is still broken, so this won't work. It should be

```
SHPOOL__OLD_PROMPT_COMMAND="${{PROMPT_COMMAND[@]}}"
```

Here is a shell session showing what I mean:

```
$ ARR1=("foo bar" "bim bap")
$ echo ${ARR1[0]}
foo bar
$ echo ${ARR1[1]}
bim bap
$ ARR2="${ARR1}" # what we do now, bad
$ echo ${ARR2[0]}
foo bar
$ echo ${ARR2[1]} # fails

$ ARR2=("${ARR1[@]}") # what we should do
$ echo ${ARR2[0]}
foo bar
$ echo ${ARR2[1]}
bim bap
```

Comment (parrotmac) [reply libshpool/src/daemon/prompt.rs:68]: Ah, my bad, totally misunderstood that before. Makes sense now. Updated!
